spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redis-login?characterEncoding=UTF8&serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    local-cache-scope: statement
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.h2t.study.po